### ISSUE TITLE
Connect to IMAP account

### ISSUE THREAD

**Issue by mgax** [jparyani/Mailpile#2]
It's nice that the Sandstorm port creates its own email address, but I'd like to set up Mailpile to connect to my existing IMAP account, is that possible?

**Comment by jparyani** [comment]
Unfortunately, this is not possible in Sandstorm, at least for the moment. This would require an outgoing connection (POP3 or IMAP) from the app, but all outgoing connections are blocked in the sandbox. The way this may eventually work is with "device drivers" (see https://github.com/sandstorm-io/sandstorm/issues/57), but even then I imagine we'll keep it as a non-standard way to use email, since it flies in the face of the privacy guarantees of Sandstorm. The current workaround is to setup email forwarding from your email to Sandstorm's email.

Closing since email apps will have to be re-ported a bit when the powerbox + device drivers are implemented, and we'll probably pick up this ability for free.
