### ISSUE TITLE
How to: setup mail pile

### ISSUE THREAD

**Issue by JamborJan** [jparyani/Mailpile#5]
I played a bit with mail pile on sandstorm and didn't figure out how to set it up to be actually used.

My current ideas how it could be setup are like this:
- Somehow my sandstorm server needs to be able to send mail or to redirect this Question: how can this be done? Only with the mail parameter in sandstorm.conf?
- How can I connect that to my email provider?
- Or how do I match my email address which I want to use e.g. jan@jambor.pro with that cryptic one in Mailpile e.g.  78xm3taqdd8kypet17uc@something.differe.nt
- how can I upload my existing PGP keys? The find keys feature is broken (see https://github.com/jparyani/Mailpile/issues/6)

Thanks for help here.

PS: Tested with Sandstorm 0.68 and Mailpile version Feb 6 2015.

**Comment by jparyani** [comment]
> Somehow my sandstorm server needs to be able to send mail or to redirect this Question: how can this be done? Only with the mail parameter in sandstorm.conf?

See https://github.com/sandstorm-io/sandstorm/wiki/Configuring-your-server-for-email. The MAIL_URL parameter is for outgoing mail. You also need to setup incoming. The wiki doesn't cover it, but if you're comfortable with setting up an MTA, you could do it that way as well.

> How can I connect that to my email provider?
> Or how do I match my email address which I want to use e.g. jan@jambor.pro with that cryptic one in Mailpile e.g. 78xm3taqdd8kypet17uc@something.differe.nt

These 2 seem like the same question to me, let me know what I'm missing. For now, we don't have a really good story for getting nice, readable addresses like jan@DOMAIN out of sandstorm. The current recommendation is to setup mail forwarding with your current mail provider to the cryptic Sandstorm email address.

> how can I upload my existing PGP keys? The find keys feature is broken (see #6)

I'll answer more extensively on #6, but in short, you can't. We removed all the nice GPG functionality from Mailpile, since its security model is predicated on the keys being on your local server that you fully control.

**Comment by jmatsushita** [comment]
It would be great if these instructions appeared in the "Sandstorm FAQ" page or somewhere easy for a sandstorm admin to find. I had to chase this issue to move forward with configuring mailpile.

**Comment by jparyani** [comment]
Sorry this issue is a bit out of date. All of our docs have moved to https://docs.sandstorm.io, specificially https://docs.sandstorm.io/en/latest/administering/ for admin related stuff.

**Comment by JamborJan** [comment]
I've no need for this anymore.
